//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaryRecords
    {
        public int RecordID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string GradeValue { get; set; }
        public string HomeworkText { get; set; }
        public string TeacherComment { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public bool IsPresent { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Subjects Subjects1 { get; set; }
    }
}
